### ISSUE TITLE
Empty output

### ISSUE THREAD

**Issue by dmitru** [meronym/speaker-transcription#1]
Using the stock input:

Running predict()...
pre-processing audio file...
Input #0, image2, from '/tmp/tmpvplq5ejv1678544615656.jpg':
Duration: 00:00:00.04, start: 0.000000, bitrate: 148832 kb/s
Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 2718x3624 [SAR 1:1 DAR 3:4], 25 tbr, 25 tbn, 25 tbc
Output #0, wav, to '/tmp/tmpxy7_d_va/audio.wav':
Output file #0 does not contain any stream
transcribing segments...

**Comment by meronym** [comment]
@dmitru Looks like the input file is a `.jpg` image (as shown by the `ffmpeg` output). The model is supposed to be used with audio or video files. What do you mean by the stock input?

**Comment by olefirenko** [comment]
I have the same issue, even though I am passing the mp3 file. This is the link to the audio file https://fdczvxmwwjwpwbeeqcth.supabase.co/storage/v1/object/public/audios/27feb2bb-aeb4-4a83-9fb6-8f3f2a15885e/f52da48a-07d8-4381-8819-e69d7b05970d

**Comment by meronym** [comment]
Seems to be fixed now

**Comment by olefirenko** [comment]
Thanks a lot!
